### ISSUE TITLE
Docker hosted .NET Core application "proxy"

### ISSUE THREAD

**Issue by oldyoucal** [oldyoucal/netcoredockerproxy#1]
**Create a ASP.NET Core application hosted in a Docker container that:**

- Creates a new outgoing http request to a specified URL from an incoming http request
- Adds client certificate authentication for a specified certificate on the outgoing request
- The application and certificate should be deployed in a Docker container

Example: Incoming request -> .NET Core App in Docker -> Outgoing request to URL (authenticated with cert) -> Return 200 OK

Incoming request: 
`curl -v --request POST https://URLTODOCKERHOSTAPP \     --header "Content-Type: application/json" \     --data @- <<! {     "payeePaymentReference": "0123456789",     "callbackUrl": "https://example.com/api/swishcb/paymentrequests",     "payerAlias": "4671234768",     "payeeAlias": "1231181189",     "amount": "100", "currency": "SEK",     "message": "Kingston USB Flash Drive 8 GB" } `

Outgoing request (cert authenticated):
`curl -v --request POST https://mss.swicpc.bankgirot.se/swishcpcapi/api/v1/paymentrequests \     --header "Content-Type: application/json" \     --data @- <<! {    SAME BODY AS INCOMING REQUEST }`
This request should be implemented in .NET Core in a Controller action.

Client cert: https://developer.getswish.se/merchants-test-con/1-introduction/ (download as zip), cert in (Guide_+_Testcertificates_171024\Testcertifikat)
Swish documentation: https://developer.getswish.se/merchants-test-con/1-introduction/

**Deliverables:**

- .NET Core Source code
- Docker container
- Docker compose that installs the certificate and the .NET Core application
- An automated test that calls the application in the docker container and returns the response from the outgoing request
- Instructions on how to set up environment so test can be run with correct result

**Comment by alexandrustanimir** [comment]
@youcal Currently swish API is not available. On Friday it was working well. Is there any other API to be tested?

**Comment by oldyoucal** [comment]
Hi! There is no other API. We are not the hosters of the API. Is it down today too?

**Comment by alexandrustanimir** [comment]
@youcal Now it is working fine 👍

**Comment by oldyoucal** [comment]
Ok, let me know when you are done so I can review it.

**Comment by alexandrustanimir** [comment]
@youcal  I have create a PR here https://github.com/youcal/netcoredockerproxy/pull/2

**Comment by carl-youcal** [comment]
@alexandrustanimir We were able to build the docker container and host the application, but the single test in the test project fails because ProxyController returns a status code of 500. I'd assume that this is because the application is unable to locate the certificate chain when making the request to the Swish API and that the code which installs the certificate collection in the startup class doesn't fully work.

Output stack trace from docker:
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLCJME24FIF0", Request id "0HLCJME24FIF0:00000001": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: SSL connect error
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DockerProxyCore.Controllers.ProxyController.<Create>d__2.MoveNext() in /src/DockerProxyCore/Controllers/ProxyController.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
```

Docker version:
```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:06:28 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:14:32 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

Let us know if there are any more specifics you need from us to help you debug this issue.

**Comment by oldyoucal** [comment]
The reason why we are running Linux is to be able to host it in Azure App Service container hosting.

**Comment by alexandrustanimir** [comment]
@youcal Unfortunately this is a known issue in dotnet core 2.0 with linux. Even if the certificate is deployed, there is a problem with authenticating requests because the private key is missing. https://github.com/dotnet/corefx/issues/22996
I will try to find an workaround for this.

**Comment by oldyoucal** [comment]
That would be great. Linux hosting is key. Will add $50 if solved.

**Comment by alexandrustanimir** [comment]
Quick update on this. I have tried without luck to use .net core 2.1 preview since they claimed that should fixed this issue ( https://github.com/dotnet/corefx/issues/19718 ) by using SocketsHttpHandler. Now I am trying to find another option to configure manually the certificate within docker image.

**Comment by alexandrustanimir** [comment]
@youcal I switched to Ubuntu, installed manually test certificate and after running `curl -v --request POST https://mss.swicpc.bankgirot.se/swish-cpcapi/api/v1/paymentrequests ` I am getting this error : 
error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure. I think that there is an issue with the certificate.
 There is also a new question open on StackOverflow related to this https://unix.stackexchange.com/questions/435774/using-curl-with-certificates-on-ubuntu-16-04

**Comment by alexandrustanimir** [comment]
@youcal @carl-youcal I have updated to .net core 2.1 and everything works fine. Can you please have a look ?
